# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sga_paperclippolymorph}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tim.teng"]
  s.date = %q{2010-08-03}
  s.description = %q{gem version of paperclippolymorph for sga company}
  s.email = %q{tim.rubist@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "generators/polymorphic_paperclip/USAGE",
     "generators/polymorphic_paperclip/polymorphic_paperclip_generator.rb",
     "generators/polymorphic_paperclip/templates/migration.rb",
     "lib/sga/acts_as_polymorphic_paperclip.rb",
     "lib/sga/asset.rb",
     "lib/sga/attaching.rb",
     "lib/sga_paperclippolymorph.rb",
     "sga_paperclippolymorph.gemspec",
     "test/helper.rb",
     "test/test_sga_paperclippolymorph.rb"
  ]
  s.homepage = %q{http://github.com/tteng/sga_paperclippolymorph}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{gem version of paperclippolymorph for sga company}
  s.test_files = [
    "test/test_sga_paperclippolymorph.rb",
     "test/helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paperclip>, [">= 2.3.3"])
    else
      s.add_dependency(%q<paperclip>, [">= 2.3.3"])
    end
  else
    s.add_dependency(%q<paperclip>, [">= 2.3.3"])
  end
end

